### PR TITLE
Specify source/target language version explicitly and add required sections to pom.xml

### PR DESCRIPTION
**Pull request by akamensky**
This PR closes issue #4 and adds required sections to pom.xml in order to make artifact publishable to Maven Central

### CODE REVIEW

**Comment by augustl** [comment]
Thanks a lot!

**Comment by akamensky** [comment]
@augustl 

BTW, I left email empty, but it is required by sonatype repository.

Also could add same way of automated releases using Travis CI (artifacts will be automatically uploaded once master branch was tagged). I could do PR for those, but also it would require you to setup Travis CI and add encrypted variables to its config.

**Comment by augustl** [comment]
Currently struggling with making gpg signing work. After that, I'll grok what sonatype is. I'll let you know when it's been published to maven central!

**Comment by akamensky** [comment]
Great, thanks a lot!

**Comment by augustl** [comment]
I finally managed to figure out that I had to file an issue so hopefully it'll get resolved soon so I can deploy to the sonatype repos.

**Pull request merged**
